// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function ListFonts() {
  return window['go']['main']['App']['ListFonts']();
}

export function PickAndScan() {
  return window['go']['main']['App']['PickAndScan']();
}

export function Rescan() {
  return window['go']['main']['App']['Rescan']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}
