// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {http} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetLibrary():Promise<model.Library>;

export function ListFonts():Promise<Array<string>>;

export function PickAndScan():Promise<model.Library>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
